name: Deploy to Railway

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway
        run: railway up --service ubio-tt
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}